from django.urls import path
from  backend import views

urlpatterns=[
    path('indexpage/',views.indexpage,name="indexpage"),
    path('des_page/', views.des_page, name="des_page"),
    path('save_destination/', views.save_destination, name="save_destination"),
    path('display_des/', views.display_des, name="display_des"),
    path('edit_des/<int:destid>/', views.edit_des, name='edit_des'),
    path('update_des/<int:destid>/', views.update_des, name='update_des'),
    path('delete_page/<int:destid>/', views.delete_page, name='delete_page'),
    path('packages/', views.packages, name='packages'),
    path('save_package/', views.save_package, name='save_package'),
    path('display_packages/', views.display_packages, name='display_packages'),
    path('edit_pack/<int:packid>/', views.edit_pack, name='edit_pack'),
    path('update_package/<int:packid>/', views.update_package, name='update_package'),
    path('delete_package/<int:packid>/', views.delete_package, name='delete_package'),
    path('hotel_page/', views.hotel_page, name='hotel_page'),
    path('save_hotel/', views.save_hotel, name='save_hotel'),
    path('display_hotel/', views.display_hotel, name='display_hotel'),
    path('edit_hotel/<int:hotelid>/', views.edit_hotel, name='edit_hotel'),
    path('update_hotel/<int:hotelid>/', views.update_hotel, name='update_hotel'),
    path('delete_hotel/<int:hotelid>/', views.delete_hotel, name='delete_hotel'),
    path('hotel_details/', views.hotel_details, name='hotel_details'),
    path('save_hotel_details/', views.save_hotel_details, name='save_hotel_details'),
    path('display_details/', views.display_details, name='display_details'),
    path('edit_details/<int:detid>/', views.edit_details, name='edit_details'),
    path('update_hotel_details/<int:detid>/', views.update_hotel_details, name='update_hotel_details'),
    path('delete_hotel_details/<int:detid>/', views.delete_hotel_details, name='delete_hotel_details'),
    path('login_pages/', views.login_pages, name='login_pages'),
    path('admin_login/', views.admin_login, name='admin_login'),
    path('admin_logout/', views.admin_logout, name='admin_logout'),
    path('contact_data/', views.contact_data, name='contact_data'),
    path('delete_contact/<int:conid>/', views.delete_contact, name='delete_contact'),
    path('mail_page/', views.mail_page, name='mail_page'),
    path('activity/', views.activity, name='activity'),
    path('save_activity/', views.save_activity, name='save_activity'),
    path('edit_activity/<int:acid>/', views.edit_activity, name='edit_activity'),
    path('display_activities/', views.display_activities, name='display_activities'),
    path('update_activity/<int:acid>/', views.update_activity, name='update_activity'),
    path('delete_act/<int:acid>/', views.delete_act, name='delete_act'),

]
