# Generated by Django 4.2.7 on 2024-02-27 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinationdb',
            old_name='country',
            new_name='place',
        ),
    ]
