# Generated by Django 4.2.7 on 2024-03-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_country_destinationdb_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedb',
            name='profile4',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
