# Generated by Django 4.2.7 on 2024-03-05 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_packagedb_profile4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagedb',
            old_name='country1',
            new_name='country',
        ),
    ]
