# Generated by Django 4.2.7 on 2024-03-05 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_country1_packagedb_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagedb',
            old_name='country',
            new_name='country1',
        ),
        migrations.RemoveField(
            model_name='packagedb',
            name='profile4',
        ),
    ]
