# Generated by Django 4.2.7 on 2024-03-05 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_country_packagedb_country1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagedb',
            old_name='country1',
            new_name='country2',
        ),
    ]
