# Generated by Django 4.2.7 on 2024-03-06 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_rename_country1_packagedb_country2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagedb',
            old_name='country2',
            new_name='country1',
        ),
    ]
