# Generated by Django 4.2.7 on 2024-03-08 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_packagedb_price_remove_packagedb_profile4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagedb',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='packagedb',
            name='hotel',
        ),
    ]
