# Generated by Django 4.2.7 on 2024-03-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_remove_packagedb_detail_remove_packagedb_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='hoteldb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=500, null=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='profile')),
            ],
        ),
    ]
