# Generated by Django 4.2.7 on 2024-03-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_hoteldb'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotel_detailsdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('profile1', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('profile2', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('profile3', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('profile4', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('profile5', models.ImageField(blank=True, null=True, upload_to='profile')),
            ],
        ),
        migrations.AddField(
            model_name='packagedb',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
