# Generated by Django 4.2.7 on 2024-03-18 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_hotel_detailsdb_packagedb_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagedb',
            name='price',
        ),
    ]
