# Generated by Django 4.2.7 on 2024-03-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_remove_packagedb_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedb',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
