# Generated by Django 4.2.7 on 2024-04-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_packagedb_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='activitidb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(blank=True, max_length=500, null=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='profile')),
            ],
        ),
    ]
