# Generated by Django 4.2.7 on 2024-07-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_activitidb'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitidb',
            name='hour',
            field=models.IntegerField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='activitidb',
            name='price',
            field=models.IntegerField(blank=True, max_length=500, null=True),
        ),
    ]
