# Generated by Django 4.2.7 on 2024-02-23 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frntend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contactdb',
        ),
    ]
