# Generated by Django 4.2.7 on 2024-02-23 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frntend', '0002_rename_contact_contactdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdb',
            old_name='address',
            new_name='email',
        ),
    ]
