# Generated by Django 4.2.7 on 2024-03-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frntend', '0006_booking_placedb'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkoutdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.IntegerField(blank=True, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('cash', models.CharField(blank=True, max_length=100, null=True)),
                ('online', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
