# Generated by Django 4.2.7 on 2024-04-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frntend', '0007_checkoutdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='checkoutdb',
        ),
        migrations.RemoveField(
            model_name='contactdb',
            name='number',
        ),
        migrations.AddField(
            model_name='contactdb',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactdb',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactdb',
            name='message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
