# Generated by Django 4.2.7 on 2024-04-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frntend', '0009_paymentdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotelbookdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('checkin', models.DateField(blank=True, null=True)),
                ('checkout', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='idimage2')),
                ('room', models.IntegerField(blank=True, null=True)),
                ('adult', models.IntegerField(blank=True, null=True)),
                ('children', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
