# Generated by Django 4.2.7 on 2024-04-08 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frntend', '0010_hotelbookdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hotelbookdb',
            new_name='htbookdb',
        ),
    ]
