# Generated by Django 4.2.7 on 2024-07-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frntend', '0012_resrvationdb_delete_htbookdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resrvationdb',
            name='ch_in',
            field=models.DateField(blank=True, null=True),
        ),
    ]
