# Generated by Django 4.2.7 on 2024-07-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frntend', '0013_alter_resrvationdb_ch_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='actdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
